<div class="content-box">
    <div style="margin-top: 50px; padding: 0px 10%">
        <h1 style="font-size: 30px !important;text-align: center">ABOUT US</h1>
        <hr>
        <p>
            Trang web tổng hợp phân loại tất cả sản phẩm đang được bán giảm giá tại các trang web nổi tiếng như forever21, levi.com, target.com, overstock.com, drugstore.com,...
            <br>Bạn có thể truy cập, tìm kiếm các sản phẩm giảm giá mình yêu thích và đi đến các trang bán sản phẩm để mua hàng.
            <br>Bạn có thể đăng ký một website bán hàng, hệ thống sẽ tự động tổng hợp các sản phẩm giảm giá mà trang web của bạn đang bán.
            <br>Hoặc bạn có thể chia sẻ một sản phẩm giảm giá trên hệ thống bằng chức năng add product
        </p>
    </div>
</div>

<script>
    $('.head .box-search').remove();
</script>