<div class="footer">
    <br>
    <br>
    <br>
    <div style="border-top: 1px solid #cbcbcb; border-bottom: 1px solid #FFFFFF; height:0px; margin-left:1px;"></div>
    <div class="box_footer">
        <div style="border-top: medium none;color: #4194bb;margin: 0 auto; text-align: center;width: 85%;">
            <div>
                <!-- start SITE_WIDE_FOOTER_CC -->
                <div class="ftr">
                    <table cellspacing="0" cellpadding="0" width="100%">
                        <tbody>
                        <tr>
                            <td style="text-align: left; padding: 20px 0px;">
                                <span class="footerTitle" style="color: #F06E10; font-weight: bold;">About Us</span>
                                <br /><br />
                                <ul>
                                    <li style="padding: 5px 0px 0px 0px;" >
                                        <a href="/index/about">About us</a>
                                    </li>
                                    <li style="padding: 5px 0px 0px 0px;" >
                                        <a href="/index/faq">FAQ</a>
                                    </li>
                                    <li><a>Contact us</a></li>
                                </ul>
                            </td>
                            <td style="text-align: left; padding: 20px 0px;">
                                <span class="footerTitle" style="color: #F06E10; font-weight: bold;">Social Network</span>
                                <br /><br />
                                <ul>
                                    <li style="padding: 5px 0px 0px 0px;" >
                                        <a>Facebook</a>
                                    </li>
                                    <li style="padding: 5px 0px 0px 0px;" >
                                        <a>Twite</a>
                                    </li>
                                    <li style="padding: 5px 0px 0px 0px;" >
                                        <a>Facebook</a>
                                    </li>
                                </ul>
                            </td>
                            <td style="text-align: left; padding: 10px 0px;">
                                <div class="countries-title" style="padding: 5px 0px;color: #333333;">Ads Link:</div>
                                <ul class="countries-list clearfix">
                                    <li style="display: inline; margin-right: 10px;">
                                        <a style="color: #F06E10;" target="_blank" href="http://codecloud.vn/">Thông tin công nghệ</a>
                                    </li>
                                    |
                                    <li style="display: inline; margin-right: 10px;">
                                        <a style="color: #F06E10;" target="_blank" href="http://lenocnha.com/">Nhạc sàn hay</a>
                                    </li>
                                    |
                                    <li style="display: inline; margin-right: 10px;">
                                        <a style="color: #F06E10;" target="_blank" href="http://chotam.info/">Rao vặt</a>
                                    </li>
                                </ul>
                                <div class="clearfix"></div>
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:0px;" colspan="3">
                                <div style="border-top: 1px solid #cbcbcb; border-bottom: 1px solid #FFFFFF; height:0px; margin-left:1px;"></div>
                            </td>
                        </tr>

                        </tbody>
                    </table>
                </div>
                <!-- end SITE_WIDE_FOOTER_CC -->
            </div>
            <div style="padding: 15px;color: #333333;">
                Copyright &copy; 2016 Sale World 18
                <br />
                Contact: thamhut@gmail.com
            </div>
        </div>
        <!-- google_ad_section_end(weight=ignore) -->
    </div>

</div>