<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link href="favicon.ico" rel="shortcut icon" type="image/x-icon" />

    <link rel="alternate" href="http://lenocnha.com" hreflang="vi-vn" />
    <?php echo Phalcon\Tag::getTitle(); ?>
    <meta name="GENERATOR" content="NhacSan"/>
    <link rel="canonical" href="http://lenocnha.com/"/>
    <meta name="title" content="<?php echo (isset($meta_title)&&$meta_title!='')?'Nhac San : '.$meta_title:'DJ - Nghe Nhạc Sàn Nhạc DJ Cực Mạnh Mới Nhất 2016' ?>">
    <meta name="description" content="<?php echo (isset($meta_content)&&$meta_content!='')?'Nhac San : '.$meta_content:'lenocnha.com Lên Nóc Nhà nghe Nhạc Sàn hay nhất Nhạc DJ cực mạnh Nonstop sôi động nhất tất cả Nhạc Sàn DJ hay nhất Việt Nam' ?>.">
    <meta name="keywords" content="len noc nha, nhac san, nhac nonstop, nhac vu truong, nhac dj, nhac remix hay nhat">
    <meta name="robots" content="index, follow, all" />
    <meta content='index, follow' name='GOOGLEBOT' />
    <meta content='index, follow' name='yahooBOT' />
    <meta name="Slurp" content="index,follow" />
    <meta name="revisit-after" content="1 days" />
    <meta name="MSNBot" content="index,follow" />
    <meta http-equiv="Content-Language" content="vi" />
    <meta name="revisit-after" content="1 days" />
    <meta property="article:author" content="https://www.facebook.com/H%E1%BB%99i-Thanh-Ni%C3%AAn-Bay-V%C3%AC-Nh%E1%BA%A1c-S%C3%A0n-Lan-Man-Nh%E1%BA%A1c-Nonstop-Stop-C%C3%B9ng-Nh%E1%BA%A1c-Dj-1405309099768590/?ref=bookmarks"/>
    <meta name="abstract" content="nghe nhạc,tải nhạc,download nhạc,nhạc trực tuyến,nghe nhạc trực tuyến,tải nhạc trực tuyến"/>
    <meta HTTP-EQUIV="PRAGMA" CONTENT="PUBLIC">
    <meta vary="User-Agent"/>
    <meta content='Ong Trum' name='Author'/>
    <meta content='general' name='rating'/>
    <meta name='geo.placename' content='Ha Noi, Viet Nam'/>
    <meta name='ICBM' content='21.021691, 105.824931' />
    <meta name='geo.position' content='21.021691; 105.824931' />
    <meta name='geo.posion' content='VN-Hanoi' />
    <meta name="DC.subject" content="<?php echo (isset($meta_title)&&$meta_title!='')?'Nhac San : '.$meta_title:'DJ - Nghe Nhạc Sàn Nhạc DJ Cực Mạnh Mới Nhất 2016' ?>">
    <meta name="DC.language" scheme="UTF-8" content="vi">
    <link rel="alternate feed" type="application/rss+xml" title="Sitemap" href="http://lenocnha.com/sitemap.xml" />
    <link rel="schema.DC" href="http://purl.org/dc/elements/1.1/">
    <meta name="DC.title" content="<?php echo (isset($meta_title)&&$meta_title!='')?'Nhac San : '.$meta_title:'DJ - Nghe Nhạc Sàn Nhạc DJ Cực Mạnh Mới Nhất 2016' ?>">
    <meta name="DC.identifier" content="http://lenocnha.com/">
    <meta name="DC.description" content="<?php echo (isset($meta_content)&&$meta_content!='')?'Nhac San : '.$meta_content:'lenocnha.com Lên Nóc Nhà nghe Nhạc Sàn hay nhất Nhạc DJ cực mạnh Nonstop sôi động nhất tất cả Nhạc Sàn DJ hay nhất Việt Nam' ?>.">
    <meta name="DC.subject" content="<?php echo (isset($meta_title)&&$meta_title!='')?'Nhac San : '.$meta_title:'DJ - Nghe Nhạc Sàn Nhạc DJ Cực Mạnh Mới Nhất 2016' ?>">
    <meta name="DC.language" scheme="UTF-8" content="vi">
    <meta property="og:image" content="http://lenocnha.com/public/img/share/<?php echo(rand(1,100)); ?>.jpg" alt="Nhac San"/>
    <meta property="og:title" content="<?php echo (isset($meta_title)&&$meta_title!='')?'Nhac San : '.$meta_title:'DJ - Nghe Nhạc Sàn Nhạc DJ Cực Mạnh Mới Nhất 2016' ?>"/>
    <meta property="og:url" content="http://lenocnha.com{{ router.getRewriteUri() }}"/>
    <meta property="og:site_name" content="lenocnha.com - Nhạc Sàn Số 1 Việt Nam"/>
    <meta property="og:description" content="<?php echo (isset($meta_content)&&$meta_content!='')?'Nhac San : '.$meta_content:'lenocnha.com Lên Nóc Nhà nghe Nhạc Sàn hay nhất Nhạc DJ cực mạnh Nonstop sôi động nhất tất cả Nhạc Sàn DJ hay nhất Việt Nam' ?>"/>
    <link rel="image_src" href="http://lenocnha.com/public/img/logo.png" alt="Nhac San"/>
    <?php echo $this->assets->outputCss() ?>
    <?php echo $this->assets->outputJs() ?>
</head>