<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link href="favicon.ico" rel="shortcut icon" type="image/x-icon" />

    <link rel="alternate" href="http://saleworld18.com" hreflang="en-us" />
    <?php echo Phalcon\Tag::getTitle(); ?>
    <meta name="GENERATOR" content="Sale world"/>
    <link rel="canonical" href="http://saleworld18.com/"/>
    <meta name="title" content="<?php echo $meta_title; ?>">
    <meta name="description" content="<?php echo $meta_content; ?>.">
    <meta name="keywords" content="sale, deal, clothes, clothing, apparel, casual tops, dressy tops, basics, skirts, dress, dresses, sale, fashion, cheap, tees, tank tops, graphics, shirts, pants, jeans, shorts, sweaters, outerwear, jackets, tops, bottoms, skirts, shoes, halter, tube top, denim, jewelery, accessories, rings, necklaces, underwear, mens, womens, woman, junior fashion, xxi, forlove, gadzooks, womens apparel, intimate, handbags, sunglasses, hats, scarves, hair goods, earrings">
    <meta name="robots" content="index, follow, all" />
    <meta content='index, follow' name='GOOGLEBOT' />
    <meta content='index, follow' name='yahooBOT' />
    <meta name="Slurp" content="index,follow" />
    <meta name="revisit-after" content="1 days" />
    <meta name="MSNBot" content="index,follow" />
    <meta http-equiv="Content-Language" content="en" />
    <meta HTTP-EQUIV="PRAGMA" CONTENT="PUBLIC">
    <meta vary="User-Agent"/>
    <meta content='Ong Trum' name='Author'/>
    <meta content='general' name='rating'/>
    <meta name='geo.placename' content='Americas, New York'/>
    <meta name='ICBM' content='40.7058316, -74.2581956' />
    <meta name='geo.position' content='40.7058316, -74.2581956' />
    <meta name='geo.region' content='US-NY' />
    <meta name="DC.subject" content="<?php echo $meta_title; ?>">
    <meta name="DC.language" scheme="UTF-8" content="en">
    <link rel="alternate feed" type="application/rss+xml" title="Sitemap" href="http://saleworld18.com/sitemap.xml" />
    <link rel="schema.DC" href="http://purl.org/dc/elements/1.1/">
    <meta name="DC.title" content="<?php echo $meta_title; ?>">
    <meta name="DC.identifier" content="http://saleworld18.com/">
    <meta name="DC.description" content="<?php echo $meta_content; ?>.">
    <meta property="og:image" content="http://lenocnha.com/public/img/share/<?php echo(rand(1,100)); ?>.jpg" alt="Nhac San"/>
    <meta property="og:title" content="<?php echo $meta_title; ?>"/>
    <meta property="og:url" content="http://saleworld18.com<?php $router = new Phalcon\Mvc\Router; echo  $router->getRewriteUri(); ?>"/>
    <meta property="og:site_name" content="aggregate products about clothes fashion sale off..."/>
    <meta property="og:description" content="<?php echo $meta_content; ?>"/>
    <link rel="image_src" href="http://saleworld18.com/skin/common/img/logo.png" alt="Sale world"/>
    <?php echo $this->assets->outputCss() ?>
    <?php echo $this->assets->outputJs() ?>
</head>