<div id="pagination">
    <ul>
        <li><a href="<?php echo $data['url']; ?>"><<</a></li>
        <?php if ($data_content['before'] < $data_content['current']) { ?>
        <li><a onclick=""><</a></li>
        <?php } ?>
        <?php if ($data_content['current'] > 3) { ?>
        <li><a href="<?php echo $data['url']; ?>&page=<?php echo $data_content['current'] - 2; ?>"><?php echo $data_content['current'] - 2; ?></a></li>
        <?php } ?>
        <?php if ($data_content['current'] > 2) { ?>
        <li><a href="<?php echo $data['url']; ?>&page=<?php echo $data_content['current'] - 1; ?>"><?php echo $data_content['current'] - 1; ?></a></li>
        <?php } ?>
        <li><a class="current" href="<?php echo $data['url']; ?>&page=<?php echo $data_content['current']; ?>"><?php echo $data_content['current']; ?></a></li>
        <?php if ($data_content['current'] < ($data_content['last'] - 1)) { ?>
        <li><a href="<?php echo $data['url']; ?>&page=<?php echo $data_content['current'] + 1; ?>"><?php echo $data_content['current'] + 1; ?></a></li>
        <?php } ?>
        <?php if ($data_content['current'] < ($data_content['last'] - 2)) { ?>
        <li><a href="<?php echo $data['url']; ?>&page=<?php echo $data_content['current'] + 2; ?>"><?php echo $data_content['current'] + 2; ?></a></li>
        <?php } ?>
        <?php if ($data_content['current'] < $data_content['next']) { ?>
        <li><a href="<?php echo $data['url']; ?>&page=<?php echo $data_content['next']; ?>">></a></li>
        <?php } ?>
        <li><a href="<?php echo $data['url']; ?>&page=<?php echo $data_content['last']; ?>">>></a></li>
    </ul>
</div>

<style>
    #pagination li{
        display:inline;
        padding: 7px;
        vertical-align: middle;
        border-bottom: 0px;
    }
    #pagination{height: 40px;text-align: right;}
    #pagination ul{margin-top:10px;}
    .current{font-weight: bold; text-decoration: underline !important;color:#F60!important;}
</style>