<?php
	$user = $this->session->get('auth');
?>
<div class="box-head">
	<div class="head">
		<div id="logo"><a href="/"><img alt="" src="/public/skin/common/img/logo.png" /></a></div>
		<div class="login">
			<?php if(isset($user['username'])):?>
				<div class="dropdown" style="display: table-cell; vertical-align: middle">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<i class="glyphicon glyphicon-user"></i>
						<span><?php echo $user['username'] ?> <i class="caret"></i></span>
					</a>
					<ul class="dropdown-menu">
						<li><a href="/backend/index/index">Profile</a></li>
						<li><a href="/user/logout">Logout</a></li>
					</ul>
				</div>

			<?php else:?>
				<a data-toggle="modal" data-target="#myLogin">Login</a>
				<a>|</a>
				<a data-toggle="modal" data-target="#myRegister">Register</a>
			<?php endif;?>
		</div>
		<div class="box-search">
			<form style="">
				<input type="text" name="q" style="padding: 5px;border: 1px solid #DCDEE3; width: 90%">
				<a id="search" class="fa fa-search"></a>
			</form>
		</div>
		<div class="login" style="float: right">
			<a href="/index/about">About us</a><a>|</a><a>Contact us</a><a>|</a><a href="/index/faq">FAQs</a>
		</div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="myLogin" role="dialog">
	<div class="modal-dialog">

		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Login</h4>
			</div>
			<div class="modal-body">
				<form id="frm-login" method="post">
					<div class="form-group">
						<label>Username</label>
						<input type="text" class="form-control" id="username" name="username">
					</div>
					<div class="form-group">
						<label>Password</label>
						<input type="password" class="form-control" id="password" name="password">
					</div>
					<div class="form-group text-center">
						<a class="btn btn-default" id="sm-login">Login</a>
					</div>
				</form>
			</div>
		</div>

	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="myRegister" role="dialog">
	<div class="modal-dialog">

		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Register</h4>
			</div>
			<div class="modal-body">
				<form id="frm-register" method="post">
					<div class="form-group">
						<label>Username (*)</label>
						<input type="text" class="form-control" id="username" name="username">
					</div>
					<div class="form-group">
						<label>Password (*)</label>
						<input type="password" class="form-control" id="password" name="password">
					</div>
					<div class="form-group">
						<label>RePassword (*)</label>
						<input type="password" class="form-control" id="repassword" name="repassword">
					</div>
					<div class="form-group">
						<label>Fullname</label>
						<input type="text" class="form-control" id="fullname" name="fullname">
					</div>
					<div class="form-group">
						<label>Email</label>
						<input type="text" class="form-control" id="email" name="email">
					</div>
					<div class="form-group text-center">
						<a class="btn btn-default" id="sm-register">Register</a>
					</div>
				</form>
			</div>
		</div>

	</div>
</div>