<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php echo $this->partial($layoutDir.'partials/header'); ?>
<body>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-77429310-1', 'auto');
    ga('send', 'pageview');

</script>
<script>

</script>
<div class="my-container">
	<?php echo $this->partial($layoutDir.'partials/top_menu'); ?>
    <?php echo $this->getContent(); ?>
    <?php echo $this->partial($layoutDir.'partials/footer'); ?>
</div>
</body>
</html>