<div class="row">
    <div class="col-sm-12">
        <div class="oe-toptool">
        	<?php echo Phalcon\Tag::linkTo(array("/system/acl-role/index", '<i class="fa fa-mail-reply"></i> '. $t->_('Back To List'), 'class' => 'btn btn-default')); ?>
            <?php echo Phalcon\Tag::linkTo(array("##", '<i class="fa fa-save"></i> '. $t->_('Save Resources'), 
            		'class' => 'btn btn-primary btn-grid-submit',
            		'data-grid' => "#grid-addRoleResource",
            		'data-method' => "POST",
            		'data-action' => $this->url->get("/system/acl-role/saveResource?idRole=$idRole"),
            )); ?>
        </div>    
    </div>
    <div class="col-md-12">
        <?php $grid->render(); ?>
    </div>
</div>